val: uvicorn --port $PORT validate:app --reload
ans: uvicorn --port $PORT answer:app --reload
sts: uvicorn --port $PORT stats:app --reload
red: uvicorn --port $PORT redis_connect:app --reload
bff: uvicorn --port $PORT backend_for_frontend:app --reload
tfk: ./traefik --configFile=traefik.toml
